#ifndef _GENETICSOUP_VERSION_HPP_
#define _GENETICSOUP_VERSION_HPP_

#define GENETICSOUP_VERSION_MAJOR 1
#define GENETICSOUP_VERSION_MINOR 0
#define GENETICSOUP_VERSION_RELEASE "alpha"
#define GENETICSOUP_VERSION_STRING "1.0-alpha"

#endif
